# daemonset-patch.yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: kube-multus
        env:
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
        - /bin/bash
        - -cex
        - |
          #!/bin/bash
          cp /tmp/multus-conf/70-multus.conf /tmp/00-multus.conf
          /entrypoint.sh \
            --multus-conf-file=/tmp/00-multus.conf
