# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

#components:
#- ../components/configmap
#- ../components/calico-node

images:
  - name: ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot
    newName: ghcr.io/k8snetworkplumbingwg/multus-cni
    newTag: v4.0.2-debug