# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
  - target:
      kind: DaemonSet
      name: kube-multus-ds
      namespace: kube-system
    path: ds-patch-robin.yaml
  - target:
      kind: ConfigMap
      name: multus-cni-config
      namespace: kube-system
    path: cni-config-patch.yaml

images:
  - name: ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot
    newName: abasitt/multus-cni-debug
    newTag: latest