---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
    - helloworld
  http:
    - route:
        - destination:
            host: helloworld
      # set the timeout to 5 seconds
      timeout: 3s
      # set the retry to 3 times
      retries:
        attempts: 2
        perTryTimeout: 2s