# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  registry: quay.io
  imagePath: calico
  calicoNetwork:
    #bgp: Enabled
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
      - blockSize: 116
        cidr: 2001:db8:42:0::/56
        encapsulation: "None"
        natOutgoing: Enabled
        nodeSelector: all()
      - blockSize: 26
        cidr: 10.244.0.0/16
        encapsulation: "None"
        natOutgoing: Enabled
        nodeSelector: all()
  nodeMetricsPort: 9091
  typhaMetricsPort: 9093

---

# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
