---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloworld-route
spec:
  hosts:
  - helloworld.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: clu2-lb-service
        port:
          number: 80