apiVersion: v1
kind: Service
metadata:
  name: clu2-lb-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: clu2-lb-service
subsets:
  - addresses:
      - ip: 172.18.255.121
    ports:
      - port: 80
