apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: redis-egressgw-dr
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: redis
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: redis.abasitt.tech