# 3: mes VS to route from sidecar to egw
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-mesh-vs
spec:
  hosts:
  - redis.abasitt.tech
  gateways:
  - mesh
  tcp:
  - match:
      #destinationSubnets: #since it's tcp, matching just on port could have wrong routing impact, advisable to use redis VIP here.
      #- $MONGODB_IP/32
      - port: 6379
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: redis
        port:
          number: 443

# 5: egw vs to route from egw to final destination
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-egw-vs
spec:
  hosts:
  - redis.abasitt.tech
  gateways:
  - redis-egressgw
  tcp:
  - match:
      - port: 443
    route:
    - destination:
        host: redis.abasitt.tech
        port:
          number: 6379
      weight: 100