---
services:
    frr_host:
        image: frrouting/frr:latest
        hostname: frr_host
        container_name: frr_host
        network_mode: host
        restart: always
        volumes:
          - frr_config:/etc/frr
        privileged: true

volumes:
  frr_config:
    driver: local
