apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: helloworld-global
spec:
  hosts:
  - helloworld.global
  ports:
  - number: 5000
    name: tcp
    protocol: TCP
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
  - address: 2001:db8:42:1::ec67