kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  ipFamily: dual  # Set to 'dual' for dual-stack
  disableDefaultCNI: true
  podSubnet: "2001:db8:42:0::/56,10.244.0.0/16"  # Specify both IPv4 and IPv6 subnets
  serviceSubnet: "2001:db8:42:1::/112,10.96.0.0/12"  # Specify both IPv4 and IPv6 subnets
