version: '3.8'

services:
  ubuntu1:
    image: ubuntu:latest
    container_name: ubuntu1
    privileged: true
    networks:
      bgp-net:
        ipv6_address: "fd00:1::2"
    volumes:
      - ./bird1.conf:/etc/bird/bird6.conf
    entrypoint: ["/bin/bash", "-c", "apt-get update && apt-get install -y bird iproute2 && mkdir -p /run/bird && bird6 -c /etc/bird/bird6.conf && sleep infinity"]

  ubuntu2:
    image: ubuntu:latest
    container_name: ubuntu2
    privileged: true
    networks:
      bgp-net:
        ipv6_address: "fd00:1::3"
    volumes:
      - ./bird2.conf:/etc/bird/bird6.conf
    entrypoint: ["/bin/bash", "-c", "apt-get update && apt-get install -y bird iproute2 && mkdir -p /run/bird && bird6 -c /etc/bird/bird6.conf && sleep infinity"]

networks:
  bgp-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fd00:1::/64"