# 3: mes VS to route from sidecar to egw
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: portal2-mesh-vs
  namespace: default
spec:
  exportTo:
  - "."
  hosts:
  - portal2.abasitt.tech
  gateways:
  - mesh
  http:
  - name: portal2-meshroute
    match:
      - authority:
          exact: "portal2.abasitt.tech:8082"
      #- port: 8082 #use port if you are sure that all the traffic from this port needs to redirect via ingress, else stick with the hostname
    route:
    - destination:
        host: istio-ingressgateway.istio-system.svc.cluster.local
        subset: upgrade-mtls
        port:
          number: 80

# 5: egw vs to route from egw to final destination
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: portal2-igw-vs
spec:
  hosts:
  - "portal2.abasitt.tech"
  gateways:
  - portal-gw
  http:
  - match:
      - authority:
          exact: "portal2.abasitt.tech:8082"
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
      weight: 100