apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: abasitt-tech
spec:
  hosts:
  - abasitt.tech
  ports:
  - number: 8180
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS